<?php

/**
 * @file
 * This file adds a library to views page or block.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function views_attach_library_views_pre_render(ViewExecutable $view) {

  $current_display = $view->current_display;
  $view_config = $view->storage->getDisplay($current_display);
  if (!empty($view_config['display_options']['display_extenders']['library_in_views_display_extender'])) {
    $libraries = explode(',', $view_config['display_options']['display_extenders']['library_in_views_display_extender']['attach_library']['attach_library']);
    foreach ($libraries as $library) {
      // Attach library to view.
      $view->element['#attached']['library'][] = trim($library);
    }
  }
}
